### ISSUE TITLE
Entity not saving when there's only one in the tree

### ISSUE THREAD

**Issue by OrfeasZ** [atampy25/quickentity-editor-next#4]
Steps to reproduce:

1. Open fresh QNE.
2. Go to tree view.
3. Click on Scene entity.
4. Change name to something else.
5. Navigate away.

On coming back the changes are discarded. Adding a new sub-entity and switching between them appears to persist the changes.

**Comment by atampy25** [comment]
Saving sub-entity changes is debounced by about 5 seconds, so if you wait that long after changing the name it should refresh the tree and save the changes. It's necessary for performance on larger entities, since unlike legacy QNE the tree is responsive to all entity changes.

I'm not sure if it's possible to improve this for switching views rather than entities; I don't remember the mechanism I used for entity switching so I'll look into it.
